/**
 * Rebuilds supabase/schema.sql from supabase/migrations/.
 *
 * The one-file schema is what the shop actually pastes into the Supabase SQL editor, so it
 * has to be every migration in order and nothing else. Keeping it by hand worked until it
 * did not: a migration added and not copied across is a database that passes every local
 * test and is missing a table in production.
 *
 *     node scripts/build-schema.mjs
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS = path.join(HERE, '..', 'supabase', 'migrations');
const OUT = path.join(HERE, '..', 'supabase', 'schema.sql');

const RULE = '-- ' + '='.repeat(74);

const PREAMBLE = `-- Badawi Shop: the whole database in one file.
--
-- Paste this into the Supabase SQL editor and run it once. It is every migration in
-- supabase/migrations/ concatenated in order, so it does the same job as \`npm run db:push\`
-- without needing the CLI, a project link, or the database password.
--
-- Running it more than once is harmless: everything here is create-if-not-exists or replaced.
--
-- Generated by scripts/build-schema.mjs. Edit the migrations, not this file.
`;

const files = (await readdir(MIGRATIONS)).filter((f) => f.endsWith('.sql')).sort();

const parts = [PREAMBLE];
for (const file of files) {
  const sql = await readFile(path.join(MIGRATIONS, file), 'utf8');
  parts.push(`\n${RULE}\n-- ${file}\n${RULE}\n${sql.trimEnd()}\n`);
}

await writeFile(OUT, parts.join(''), 'utf8');
console.log(`schema.sql rebuilt from ${files.length} migrations.`);
